apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db-blog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db-blog
    spec:
      containers:
      - name: db-blog
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
        ports:
          - name: db-blog-port
            containerPort: 3306
---

apiVersion: v1
kind: Service
metadata:
  name: db-blog-svc
spec:
  ports:
  - port: 8888
    targetPort: db-blog-port
    protocol: TCP

  selector:
    app: db-blog
