apiVersion: v1
kind: Service
metadata:
  name: full-blog-svc
spec:
  ports:
  - port: 8888
    nodePort: 31001
    targetPort: full-wp-port
    protocol: TCP
  selector:
    app: full-blog
  type: NodePort
